In [2]:
import numpy as np

In [7]:
# 1.

np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [7]:
# 2.

l1 = []
l2 = []
i = 0
while i < 2:
    i+=1
    l1.append(int(input()))
    
i = 0
while i < 2:
    i+=1
    l2.append(int(input()))
    
n1 = np.array(l1)
n2 = np.array(l2)
n3 = np.append(n1,n2)
print(n3)

1
2
3
4
[1 2 3 4]


In [10]:
# 3. 

n1 = np.array([1,2,3,4])

# dimension
print(n1.ndim)

# size
print(n1.size)

1
4


In [15]:
# 4. 

n1 = np.random.rand(7)

# original dim
print(n1.ndim)

# changing dimension (used to increase the dimension of the existing array by one more dimension, when used once)
n2 = n1[np.newaxis, :]

# new dimension
print(n2.ndim)

1
2


In [17]:
# 5.

n1 = np.random.rand(3)
n2 = np.random.rand(3)

# vertical stack
print(np.vstack((n1,n2)))

# horizontal stack
print(np.hstack((n1,n2)))

[[0.04375582 0.88190955 0.39255928]
 [0.55349663 0.55559009 0.10095381]]
[0.04375582 0.88190955 0.39255928 0.55349663 0.55559009 0.10095381]


In [19]:
# 6.

import numpy as np
n = np.array([1,2,3,4,5,1,6,2,8,9])

# np.unique returns the unique elements and return_counts gives the count
print(np.unique(n,return_counts=True))

(array([1, 2, 3, 4, 5, 6, 8, 9]), array([2, 2, 1, 1, 1, 1, 1, 1], dtype=int64))
